/**
 * $ vite-node .scripts/create-meta.tsx
 *
 * This script generates the tsx file which contains the component definitions data and hooks data scraped from JSdoc
 * comments.
 */
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

import { componentsMeta, typesMeta, utilitiesMeta } from 'src/meta';
import { kebabCase } from 'src/utils/kebabCase';

import { getUIRoot } from '.scripts/utils';

export function searchIndex(uiVersion: string) {
    const index: { title?: string; content?: string; url?: string; kind: string }[] = [];

    index.push(
        ...componentsMeta.flatMap((component) => {
            let content = component.description;

            const typeMeta = typesMeta.find((tm) => {
                return tm.name === `${component.name}Props`;
            });

            typeMeta?.properties?.forEach((prop) => {
                content += ` ${prop.name} ${prop.description} ${prop.default}`;
            });

            typeMeta?.references?.forEach((ref) => {
                const refMeta = typesMeta.find((tm) => {
                    return tm.name === ref;
                });

                refMeta?.properties?.forEach((prop) => {
                    content += ` ${prop.name} ${prop.description} ${prop.default}`;
                });
            });

            return {
                title: component.name,
                content,
                url: `/${component.slug}`,
                kind: 'Component',
            };
        }),
    );

    index.push(
        ...utilitiesMeta
            .filter((u) => u.name.startsWith('use'))
            .flatMap((utility) => {
                return {
                    title: utility.name,
                    content: utility.description,
                    url: `/hooks#${kebabCase(utility.name)}`,
                    kind: 'Hook',
                };
            }),
    );

    const filePath = 'src/search-index.ts';

    fs.writeFileSync(
        filePath,
        [
            `/** This file is generated by the ./scripts/create-meta.tsx script. This file contains data scraped from the @bspk/ui package. */`,

            `export const VERSION = '${uiVersion}' as const;`,

            `export const searchIndex = ${JSON.stringify(index, null, 2)} as const`,
        ].join('\n\n'),
    ); // Pretty format JSON

    execSync(`npx prettier --write "${filePath}"`, { stdio: 'inherit' });

    console.info('Search index complete.');
}

export function copyDocumentation(rootPath: string) {
    fs.readdirSync(rootPath).forEach((file) => {
        if (file.endsWith('.md')) {
            fs.copyFileSync(`${rootPath}/${file}`, `./src/docs/${file}`);
        }
    });
}

export function copyBspkFilesForTests(rootPath: string) {
    [
        //
        [path.resolve(__dirname, '../src/meta.ts'), 'meta.ts'],
        [path.resolve(rootPath, 'src/index.ts'), 'index.ts'],
    ].forEach(([sourceFile, fileName]) => {
        fs.mkdirSync(path.resolve(__dirname, `../tests/bspk-ui`), { recursive: true });
        fs.copyFileSync(sourceFile, path.resolve(__dirname, `../tests/bspk-ui/${fileName}`));
    });
}

export async function main() {
    const rootPath = getUIRoot();

    const uiVersion = execSync('npm view @bspk/ui version', { encoding: 'utf-8' }).trim();

    searchIndex(uiVersion);

    copyDocumentation(rootPath);

    copyBspkFilesForTests(rootPath);

    process.exit(0);
}

main();

/** Copyright 2025 Anywhere Real Estate - CC BY 4.0 */
