import { DevPhase } from '@bspk/ui/demo/utils';
import { MetaComponentName } from 'src/meta';

export const BACKLOG_COMPONENTS = [
    'Accordion',
    'AvatarGroup',
    'BottomNavigation',
    'BottomSheet',
    'Breadcrumb',
    'ButtonDock',
    'Chart',
    'DatePicker',
    'Drawer',
    'FileUpload',
    'FormField',
    'Image',
    'Img',
    'MultiSelection',
    'NavigationRail',
    'OTPInput',
    'PageControl',
    'PasswordInput',
    'PhoneNumberInput',
    'ProgressionStepper',
    'Rating',
    'SliderInput',
    'Snackbar',
    'Table',
    'TimePicker',
    'ToggleOption',
    'TopNavigation',
] as const;

export type BacklogComponentName = (typeof BACKLOG_COMPONENTS)[number];

export const COMPONENT_PHASE: Record<BacklogComponentName | MetaComponentName, DevPhase> = {
    Accordion: 'Backlog',
    Avatar: 'DesignReview',
    AvatarGroup: 'Backlog',
    Badge: 'DesignReview',
    BannerAlert: 'DesignReview',
    BottomNavigation: 'Backlog',
    BottomSheet: 'Backlog',
    Breadcrumb: 'Backlog',
    Button: 'DesignReview',
    ButtonDock: 'Backlog',
    Card: 'DesignReview',
    Chart: 'Backlog',
    Checkbox: 'DesignReview',
    CheckboxGroup: 'DesignReview',
    CheckboxOption: 'DesignReview',
    Chip: 'DesignReview',
    DatePicker: 'Backlog',
    Dialog: 'Utility',
    Divider: 'DesignReview',
    Drawer: 'Backlog',
    Select: 'DesignReview',
    SelectField: 'DesignReview',
    EmptyState: 'DesignReview',
    Fab: 'DesignReview',
    FileUpload: 'Backlog',
    FormField: 'Backlog',
    Image: 'Backlog',
    Img: 'Backlog',
    InlineAlert: 'DesignReview',
    Layout: 'Utility',
    Link: 'DesignReview',
    ListItem: 'DesignReview',
    Menu: 'DesignReview',
    MenuButton: 'Utility',
    Modal: 'WorkInProgress',
    MultiSelection: 'Backlog',
    NavigationRail: 'Backlog',
    NumberField: 'DesignReview',
    NumberInput: 'DesignReview',
    OTPInput: 'Backlog',
    PageControl: 'Backlog',
    PasswordInput: 'Backlog',
    PhoneNumberInput: 'Backlog',
    Popover: 'DesignReview',
    Portal: 'Utility',
    ProgressBar: 'DesignReview',
    ProgressCircle: 'AccessibilityReview',
    ProgressionStepper: 'Backlog',
    ProgressionStepperBar: 'DesignReview',
    Radio: 'Utility',
    RadioGroup: 'DesignReview',
    RadioOption: 'Utility',
    Rating: 'Backlog',
    SearchBar: 'DesignReview',
    SegmentedControl: 'DesignReview',
    Skeleton: 'DesignReview',
    SliderInput: 'Backlog',
    Snackbar: 'Backlog',
    StylesProviderAnywhere: 'Utility',
    StylesProviderBetterHomesGardens: 'Utility',
    StylesProviderCartus: 'Utility',
    StylesProviderCentury21: 'Utility',
    StylesProviderColdwellBanker: 'Utility',
    StylesProviderCorcoran: 'Utility',
    StylesProviderDenaliBoss: 'Utility',
    StylesProviderEra: 'Utility',
    StylesProviderSothebys: 'Utility',
    Switch: 'DesignReview',
    SwitchOption: 'DesignReview',
    TabGroup: 'DesignReview',
    Table: 'Backlog',
    Tag: 'AccessibilityReview',
    TextField: 'DesignReview',
    TextInput: 'DesignReview',
    Textarea: 'DesignReview',
    TextareaField: 'DesignReview',
    TimePicker: 'Backlog',
    ToggleOption: 'Backlog',
    Tooltip: 'DesignReview',
    TopNavigation: 'Backlog',
    Txt: 'DesignReview',
};

/** Copyright 2025 Anywhere Real Estate - CC BY 4.0 */
