/**
 * This file is generated by the ./scripts/create-meta.tsx script. This file contains data scraped from the @bspk/ui
 * package.
 */

export const VERSION = '1.0.3' as const;

export const searchIndex = [
    {
        title: 'Accordion',
        content: 'Component description coming soon. children The content of the accordion. undefined',
        url: '/accordion',
        kind: 'Component',
    },
    {
        title: 'Avatar',
        content:
            'An avatar is a visual representation of a user or entity. It can be used to display an initials, icon, image, or an overflowCount. aria-label The aria-label for the element. undefined size The size of the avatar. small color The color of the avatar. grey initials The initials to display in the avatar limited to 2 characters. undefined icon The icon to display in the avatar. undefined image The url to the image to display in the avatar. undefined overflowCount The number of notifications not displayed in a list. undefined',
        url: '/avatar',
        kind: 'Component',
    },
    {
        title: 'Badge',
        content:
            "Visual indicator for new items within a parent page represented with a numerical count of new items. count The content of the badge. If larger than 99, the badge will display '99+'. If null or undefined, the badge will\nbe hidden. undefined size The size of the badge. small variant The color variant of the badge. primary",
        url: '/badge',
        kind: 'Component',
    },
    {
        title: 'BannerAlert',
        content:
            'A visual and contextual message used to communicate an important message or notification to users relating to a status or the body content of a page. variant The color variant of the banner alert. informational onClose The function to call when the banner alert is closed. If not included the close button will not be displayed. undefined header The header of the banner alert. undefined body The body of the banner alert. undefined callToAction This property may be undefined or an object containing required CallToActionButton properties. undefined elevated Is the alert elevated. If true a drop shadow is added. false label The label of the call to action button. undefined onClick The callback function for the call to action button. undefined size The size of the call to action button. undefined',
        url: '/banner-alert',
        kind: 'Component',
    },
    {
        title: 'BottomNavigation',
        content: 'Component description coming soon. children The content of the bottom navigation. undefined',
        url: '/bottom-navigation',
        kind: 'Component',
    },
    {
        title: 'BottomSheet',
        content: 'Component description coming soon. children The content of the bottom sheet. undefined',
        url: '/bottom-sheet',
        kind: 'Component',
    },
    {
        title: 'Breadcrumb',
        content: 'Component description coming soon. children The content of the breadcrumb. undefined',
        url: '/breadcrumb',
        kind: 'Component',
    },
    {
        title: 'Button',
        content:
            "A clickable component that allows users to perform an action, make a choice or trigger a change in state. disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false onClick The function to call when the element is clicked. undefined label The label of the button. undefined icon The icon of the button. undefined showLabel Shows the button label. When label isn't showing it is used in a tooltip and as the aria-label prop. true as The element type to render as. button destructive The function of the button is destructive. false size The size of the button. medium variant The color variant of the button. primary width The width of the button. hug children If `string` is passed, it will be used as the label.\n\nIf `ReactNode` is passed, it will override the default button content. (Not recommended) undefined toolTip The tool tip text that appears when hovered. undefined",
        url: '/button',
        kind: 'Component',
    },
    {
        title: 'ButtonDock',
        content: 'Component description coming soon. children The content of the button dock. undefined',
        url: '/button-dock',
        kind: 'Component',
    },
    {
        title: 'Card',
        content:
            'Cards are often rectangular and contain various content, such as text, images, icons, multimedia, and interactive elements.\n\nThey are similar in size and shape to playing cards and are intended to encourage users to click or tap to view more details. children The content of the card. undefined showPadding Determines if the padding should be hidden. true variant Determines how the card border will appear. elevated',
        url: '/card',
        kind: 'Component',
    },
    {
        title: 'Chart',
        content: 'Component description coming soon. children The content of the chart. undefined',
        url: '/chart',
        kind: 'Component',
    },
    {
        title: 'Checkbox',
        content:
            'A control that allows users to choose one or more items from a list or turn an feature on or off. This is the base element and if used directly you must wrap it with a label. This will more often be used in the CheckboxOption or CheckboxGroup component. name The [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) of the control. undefined invalid Marks the element as invalid and displays error state theme. false disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false aria-label The aria-label for the element. undefined value The value of the control. undefined checked Marks the control as checked. false onChange The function to call when the control is checked or unchecked. undefined indeterminate If the checkbox is partially checked or\n[indeterminate](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate_state_checkboxes). false',
        url: '/checkbox',
        kind: 'Component',
    },
    {
        title: 'CheckboxGroup',
        content:
            'A group of checkboxes that allows users to choose one or more items from a list or turn an feature on or off. aria-label The aria-label for the element. undefined onChange The function to call when the checkboxes are changed. undefined name The input control name of the checkboxes. undefined options The options for the checkboxes. undefined values The values of the checked checkboxes. undefined selectAll Whether to show a select all checkbox at the top of the list. false selectAllProps The props for the select all checkbox. undefined label The label of the field. Also used as the aria-label of the checkbox. undefined description The description of the field. undefined value The value of the control. undefined',
        url: '/checkbox-group',
        kind: 'Component',
    },
    {
        title: 'CheckboxOption',
        content:
            'A control that allows users to choose one or more items from a list or turn an feature on or off. name The [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) of the control. undefined value The value of the control. undefined invalid Marks the element as invalid and displays error state theme. false disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false onChange The function to call when the control is checked or unchecked. undefined checked Marks the control as checked. false indeterminate If the checkbox is partially checked or\n[indeterminate](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate_state_checkboxes). false label The label of the field. Also used as the aria-label of the checkbox. undefined description The description of the field. undefined',
        url: '/checkbox-option',
        kind: 'Component',
    },
    {
        title: 'Chip',
        content:
            'Dynamically generated options that are suggested to the user as responses or prompts. disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false onClick The function to call when the element is clicked. undefined children The content of the chip. undefined wrap Whether the chip should wrap its content.\n\n(Not recommended) false variant The variant of the chip. filter flat Is the chip elevated or flat. If flat the drop shadow is removed. false selected Whether the chip is currently selected. false style The style of the chip. undefined',
        url: '/chip',
        kind: 'Component',
    },
    {
        title: 'DatePicker',
        content: 'Component description coming soon. children The content of the datepicker. undefined',
        url: '/date-picker',
        kind: 'Component',
    },
    {
        title: 'Dialog',
        content:
            'Dialogs display important information that users need to acknowledge. They appear over the interface and block further interactions until an action is selected. id The id of the element. If not provided one will be generated. undefined children The content of the dialog. undefined innerRef A ref to the dialog element. undefined open If the dialog should appear. false onClose Function to call when the dialog is closed. undefined placement The placement of the dialog on the screen. center hideScrim Whether the dialog should have a scrim behind it. false',
        url: '/dialog',
        kind: 'Component',
    },
    {
        title: 'Divider',
        content:
            'Horizontal thin lines that separates grouped content in a list or other containers with an optional section/group label.\n\nVertical thin lines that separates grouped content or other visual elements within a container. orientation The orientation of the divider. horizontal thickness The thickness of the divider. light padding If the divider padding is shown. true inset The inset (margin) of the divider. The value is a number between 0 and 12, which corresponds to the spacing\nsizing variables defined in the theme. The inset is applied to the left and right sides of the divider when the\norientation is horizontal, and to the top and bottom when the orientation is vertical. 0',
        url: '/divider',
        kind: 'Component',
    },
    {
        title: 'Drawer',
        content: 'Component description coming soon. children The content of the drawer. undefined',
        url: '/drawer',
        kind: 'Component',
    },
    {
        title: 'Dropdown',
        content:
            'A field element that allows users to select one option from a list of available choices. * name The [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) of the control. undefined id The id of the element. If not provided one will be generated. undefined invalid Marks the element as invalid and displays error state theme. false disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false size The size of the element. medium aria-label The aria-label for the element. undefined readOnly Determines if the element is [readonly](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly). false onChange The function to call when the selected values change. undefined isMulti Whether the menu allows multiple selections. false itemCount The number of items to display in the menu 5 renderListItem A function which given data about the list item returns additional list item props used to render the list items. undefined options Array of options to display in the dropdown undefined value Array of selected values! undefined placeholder Placeholder for the dropdown Select... placement The placement of the dropdown menu. Will be ignored if the menu is too close to the edge of the screen. bottom style The style of the dropdown. undefined activeIndex The index of the currently highlighted item. undefined isMulti Whether the menu allows multiple selections. false selectedValues The values of the selected items undefined index undefined undefined item undefined undefined menuId undefined undefined selected undefined undefined itemId undefined undefined value The value of the option. undefined label The label of the option. This is the text that will be displayed on the option. undefined',
        url: '/dropdown',
        kind: 'Component',
    },
    {
        title: 'DropdownField',
        content:
            'A component that allows users to input large amounts of text that could span multiple lines.\n\nThis component takes properties from the FormField and Dropdown components. name The [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) of the control. undefined value Array of selected values! undefined disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false options Array of options to display in the dropdown undefined size The size of the element. medium onChange The function to call when the selected values change. undefined placeholder Placeholder for the dropdown Select... readOnly Determines if the element is [readonly](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly). false placement The placement of the dropdown menu. Will be ignored if the menu is too close to the edge of the screen. bottom itemCount The number of items to display in the menu 5 required Determines if the element is [required](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required). false label The label of the field. undefined errorMessage Marks the element as invalid and displays error message.\n\nWhen an element is invalid it must display an error message explaining why it is invalid. undefined helperText The helperText of the field. undefined labelTrailing The trailing element of the label. undefined controlId The id of the control. undefined value The value of the option. undefined label The label of the option. This is the text that will be displayed on the option. undefined',
        url: '/dropdown-field',
        kind: 'Component',
    },
    {
        title: 'EmptyState',
        content:
            'A design pattern component that indicates to users that system has no content to display. children The image or icon to display in the empty state. undefined header The header of the empty state. undefined body The body of the empty state. undefined callToAction This property may be undefined or an object containing required CallToActionButton properties. undefined label The label of the call to action button. undefined onClick The callback function for the call to action button. undefined size The size of the call to action button. undefined',
        url: '/empty-state',
        kind: 'Component',
    },
    {
        title: 'Fab',
        content:
            "A button that highlights a primary action that is elevated above the body content of a page; normally fixed to the bottom right of a screen. icon The icon of the button. undefined onClick The function to call when the element is clicked. undefined as The element type to render as. button showLabel Shows the button label. When label isn't showing it is used in a tooltip and as the aria-label prop. true toolTip The tool tip text that appears when hovered. undefined label The label of the button. undefined size The size of the button. small variant The style variant of the button. primary placement The placement of the button on the container. bottom-right container The container to render the button in. local",
        url: '/fab',
        kind: 'Component',
    },
    {
        title: 'FileUpload',
        content: 'Component description coming soon. children The content of the fileupload. undefined',
        url: '/file-upload',
        kind: 'Component',
    },
    {
        title: 'FormField',
        content:
            'Wrapper component for form controls.\n\nChildren may be one of the following: TextInput, Dropdown, DatePicker, or TimePicker. required Determines if the element is [required](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required). false errorMessage Marks the element as invalid and displays error message.\n\nWhen an element is invalid it must display an error message explaining why it is invalid. undefined label The label of the field. undefined controlId The id of the control. undefined children The children of the form field. This should be a control such as TextInput, Dropdown, DatePicker, or TimePicker. undefined helperText The helperText of the field. undefined labelTrailing The trailing element of the label. undefined invalid Marks the element as invalid and displays error message. false aria-describedby The id of the control description. undefined aria-errormessage The id of the error message undefined',
        url: '/form-field',
        kind: 'Component',
    },
    {
        title: 'Image',
        content: 'Component description coming soon. children The content of the image. undefined',
        url: '/image',
        kind: 'Component',
    },
    {
        title: 'Img',
        content:
            'The Img component is used to display images on the page. src The URL of the image. undefined alt The alternative text for the image. undefined',
        url: '/img',
        kind: 'Component',
    },
    {
        title: 'InlineAlert',
        content:
            'Inline alerts provide contextual feedback messages for typical user actions with a handful of available and flexible alert messages. children The content of the inline alert. undefined variant The color variant of the inline alert. informational id The id of the inline alert. undefined',
        url: '/inline-alert',
        kind: 'Component',
    },
    {
        title: 'Layout',
        content:
            'Utility component used within other components for layout purposes. children The content of the Layout. undefined column Determines if the flex-direction should be displayed as a column. false gap The gap between the children. undefined as The element type to render as. div align Additional styles to apply to the Layout. flex-start justify Additional styles to apply to the Layout. flex-start',
        url: '/layout',
        kind: 'Component',
    },
    {
        title: 'Link',
        content:
            'This is the standalone link component. Inline links can use the native `a` element. target undefined undefined label The label of the link. undefined trailingIcon The variant of the link. Controls the icon that is displayed and link target. undefined href The [href](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a#href) of the link. undefined size The size of the link. base variant Change the color of the link to a subtle color. This is useful for links that are not primary actions, for\nexample footer menus. default',
        url: '/link',
        kind: 'Component',
    },
    {
        title: 'ListItem',
        content:
            'A hybrid interactive component that is used frequently to organize content and offers a wide range of control and navigation in most experiences.\n\nWith its flexible and simple structure, the list item element is core and can meet the needs of many uses cases.\n\nThe ListItem has three main elements: leading element, label, and trailing element.\n\nLeading elements may be one of the following [Icon](/icons), Img, Avatar.\n\nTrailing elements may be one of the following [Icon](/icons), Checkbox, ListItemButton, Radio, Switch, Tag, Txt.\n\nThe ListItemButton is a more limited Button with context specific options. active Marks the element as active and displays active state theme. false disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false readOnly Determines if the element is [readonly](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly). false as The element type to render as. div leading The leading element to display in the ListItem.\n\nLeading elements may only be one of the following [Icon](/icons), Img, Avatar. undefined label The label to display in the ListItem. undefined subText The subtext to display in the ListItem. undefined trailing The trailing element to display in the ListItem.\n\nTrailing elements may only be one of the following [Icon](/icons), Checkbox, ListItemButton, Radio, Switch, Tag,\nTxt. undefined',
        url: '/list-item',
        kind: 'Component',
    },
    {
        title: 'Menu',
        content:
            'A container housing a simple list of options presented to the user to select one option at a time. id The id of the element. If not provided one will be generated. undefined disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false itemCount The number of items to display in the menu 5 items Content to display in the menu. undefined innerRef A ref to the inner div element. undefined noResultsMessage Message to display when no results are found undefined activeIndex The index of the currently highlighted item. undefined selectedValues The values of the selected items undefined renderListItem A function which given data about the list item returns additional list item props used to render the list items. undefined isMulti Whether the menu allows multiple selections. false onChange The function to call when the selected values change. undefined disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false label The content to display in the menu item. undefined value The value of the menu item. undefined id The unique id of the menu item. undefined activeIndex The index of the currently highlighted item. undefined isMulti Whether the menu allows multiple selections. false selectedValues The values of the selected items undefined index undefined undefined item undefined undefined menuId undefined undefined selected undefined undefined itemId undefined undefined',
        url: '/menu',
        kind: 'Component',
    },
    {
        title: 'MenuButton',
        content:
            'Utility component used within top navigation. onClick The function to call when the element is clicked. undefined as The element type to render as. button',
        url: '/menu-button',
        kind: 'Component',
    },
    {
        title: 'Modal',
        content:
            'Modals display important information that users need to acknowledge. They appear over the interface and block further interactions until an action is selected. Modal is a wrapper around the Dialog component that provides a header and footer for the dialog.\n\nTODO: Add support for custom header and footer id The id of the element. If not provided one will be generated. undefined children The content of the dialog. undefined innerRef A ref to the dialog element. undefined open If the dialog should appear. false onClose Function to call when the dialog is closed. undefined placement The placement of the dialog on the screen. center hideScrim Whether the dialog should have a scrim behind it. false header Modal header. undefined description Modal description. undefined',
        url: '/modal',
        kind: 'Component',
    },
    {
        title: 'MultiSelection',
        content: 'Component description coming soon. children The content of the multi selection. undefined',
        url: '/multi-selection',
        kind: 'Component',
    },
    {
        title: 'NavigationRail',
        content: 'Component description coming soon. children The content of the navigation rail. undefined',
        url: '/navigation-rail',
        kind: 'Component',
    },
    {
        title: 'NumberField',
        content:
            'A input element that allows users to either input a numerical value or singularly increase or decrease the values by pressing the (+) or (-).\n\nThis component takes properties from the FormField and NumberInput components. name The [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) of the control. undefined id The id of the element. If not provided one will be generated. undefined value The value of the control. undefined invalid Marks the element as invalid and displays error state theme. false disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false size The size of the element. medium onChange Callback when the value changes. undefined readOnly Determines if the element is [readonly](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly). false centered If the value should be centered between the up & down buttons. false required Determines if the element is [required](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required). false label The label of the field. undefined errorMessage Marks the element as invalid and displays error message.\n\nWhen an element is invalid it must display an error message explaining why it is invalid. undefined helperText The helperText of the field. undefined labelTrailing The trailing element of the label. undefined controlId The id of the control. undefined',
        url: '/number-field',
        kind: 'Component',
    },
    {
        title: 'NumberInput',
        content:
            'A input element that allows users to either input a numerical value or singularly increase or decrease the values by pressing the (+) or (-). name The [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) of the control. undefined id The id of the element. If not provided one will be generated. undefined invalid Marks the element as invalid and displays error state theme. false disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false size The size of the element. medium aria-label The aria-label for the element. undefined readOnly Determines if the element is [readonly](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly). false value The value of the control. undefined onChange Callback when the value changes. undefined centered If the value should be centered between the up & down buttons. false max Defines the [maximum](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/max) value that is accepted. undefined min Defines the [minimum](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/min) value that is accepted. undefined',
        url: '/number-input',
        kind: 'Component',
    },
    {
        title: 'OTPInput',
        content: 'Component description coming soon. children The content of the otp input. undefined',
        url: '/otp-input',
        kind: 'Component',
    },
    {
        title: 'PageControl',
        content: 'Component description coming soon. children The content of the page control. undefined',
        url: '/page-control',
        kind: 'Component',
    },
    {
        title: 'PasswordInput',
        content: 'Component description coming soon. children The content of the password input. undefined',
        url: '/password-input',
        kind: 'Component',
    },
    {
        title: 'PhoneNumberInput',
        content: 'Component description coming soon. children The content of the phone number input. undefined',
        url: '/phone-number-input',
        kind: 'Component',
    },
    {
        title: 'Popover',
        content:
            'Brief message that provide additional guidance and helps users perform an action if needed. disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false placement The placement of the popover. top header The popover header. undefined content The content of the popover. undefined callToAction The call to action button properties. undefined children A single element that will trigger the popover when clicked. undefined label The label of the call to action button. undefined onClick The callback function for the call to action button. undefined size The size of the call to action button. undefined',
        url: '/popover',
        kind: 'Component',
    },
    {
        title: 'Portal',
        content:
            'Utility component to render children in the portals container provided by the BaseProvider.\n\nInitial SRR is supported. children The content to render in the portal. undefined container The container to render the portal in. undefined',
        url: '/portal',
        kind: 'Component',
    },
    {
        title: 'ProgressBar',
        content:
            'A progress bar is a horizontal visual indicator that let’s the user know the progression of a task or operation occurring in the background. size The size of the progressbar. large completion The current progress of the progressbar. 0 align The label alignment of the progressbar. center label The label of the progressbar. undefined',
        url: '/progress-bar',
        kind: 'Component',
    },
    {
        title: 'ProgressCircle',
        content:
            'Rotating circle or pill that indicates the status or state of completion for a process that’s part of a user flow. label The label of the progress circle. undefined size The size of the label and progress circle. medium labelPosition The position of the label in relation to the progress circle. bottom',
        url: '/progress-circle',
        kind: 'Component',
    },
    {
        title: 'ProgressionStepper',
        content:
            'A progress stepper is a horizontal visual indicator that let’s the user know the progression of the current process. steps The steps to display in the progress bar. undefined currentStep The current step in the progress bar.\n\nIf the current step is greater than the number of steps, all steps with be completed.\n\nIf the current step is less than 1, all steps will be incomplete. 0 variant The variant of the progress bar. Can be either horizontal, vertical, or widget.\n\nWhen on small width screens, the default will automatically switch to widget. horizontal name The name of the step. undefined subtext The subtext of the step. undefined touchLink The link to navigate to when the step is clicked. undefined',
        url: '/progression-stepper',
        kind: 'Component',
    },
    {
        title: 'ProgressionStepperBar',
        content:
            'Component description coming soon. stepCount The number of steps in the progress bar. undefined stepCompleted The last step completed. 0 size The size of the progress bar. undefined',
        url: '/progression-stepper-bar',
        kind: 'Component',
    },
    {
        title: 'Radio',
        content:
            'A round control that allows user to choose one option from a set. This is the base element and if used directly you must wrap it with a label. This will more often be used in the RadioOption or RadioGroup component. name The [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) of the control. undefined value The value of the control. undefined invalid Marks the element as invalid and displays error state theme. false disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false aria-label The aria-label for the element. undefined onChange The function to call when the control is checked or unchecked. undefined checked Marks the control as checked. false',
        url: '/radio',
        kind: 'Component',
    },
    {
        title: 'RadioGroup',
        content:
            'A group of radios that allows users to choose one or more items from a list or turn an feature on or off. name The [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) of the control. undefined value The value of the control. undefined onChange The function to call when the radios are changed. undefined options The options for the radios. undefined size The size of the radio group labels. undefined label The label of the field. Also used as the aria-label of the checkbox. undefined description The description of the field. undefined value The value of the control. undefined',
        url: '/radio-group',
        kind: 'Component',
    },
    {
        title: 'RadioOption',
        content:
            'A control that allows users to choose one or more items from a list or turn an feature on or off. name The [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) of the control. undefined value The value of the control. undefined invalid Marks the element as invalid and displays error state theme. false disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false onChange The function to call when the control is checked or unchecked. undefined checked Marks the control as checked. false label The label of the field. Also used as the aria-label of the checkbox. undefined description The description of the field. undefined',
        url: '/radio-option',
        kind: 'Component',
    },
    {
        title: 'Rating',
        content: 'Component description coming soon. children The content of the rating. undefined',
        url: '/rating',
        kind: 'Component',
    },
    {
        title: 'SearchBar',
        content:
            'Component description coming soon. itemCount The number of items to display in the menu 5 items Content to display in the menu. undefined noResultsMessage Message to display when no results are found undefined name The [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) of the control. undefined id The id of the element. If not provided one will be generated. undefined size The size of the element. medium aria-label The aria-label for the element. undefined placeholder The placeholder of the field. undefined inputRef The ref of the input. undefined searchValue The current value of the search bar. undefined setSearchValue Handler for state updates. undefined onSelect undefined undefined disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false label The content to display in the menu item. undefined value The value of the menu item. undefined id The unique id of the menu item. undefined',
        url: '/search-bar',
        kind: 'Component',
    },
    {
        title: 'SegmentedControl',
        content:
            "Navigation tool that organizes content across different screens and views. options The options to display. Each option has a label and an optional leading icon. undefined value The id of the selected option. undefined onChange The function to call when the option is clicked. undefined size The size of the options. medium width The width of the options. If set to 'fill', the options will fill the width of the container. If set to 'hug',\nthe options will be as wide as their content. hug showLabels Determines if the labels of the options should be displayed. If icons are not provided for every option this is\nignored and labels are shown. true label The label of the option. This is the text that will be displayed on the option. undefined disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false value The value of the option. If not provided, the label will be used as the value. undefined icon The the icon to display before the label. undefined iconActive undefined undefined",
        url: '/segmented-control',
        kind: 'Component',
    },
    {
        title: 'Skeleton',
        content:
            "A visual placeholder for an element while it is in a loading state. variant The text variant of the skeleton. If 'other' skeleton will expand to size of nearest relative positioned parent. other lines The number of lines showing. Ignored when variant is other. 1",
        url: '/skeleton',
        kind: 'Component',
    },
    {
        title: 'SliderInput',
        content: 'Component description coming soon. children The content of the slider input. undefined',
        url: '/slider-input',
        kind: 'Component',
    },
    {
        title: 'Snackbar',
        content: 'Component description coming soon. children The content of the snackbar. undefined',
        url: '/snackbar',
        kind: 'Component',
    },
    {
        title: 'StylesProviderAnywhere',
        content: 'Utility to provide the Anywhere styles to the application.',
        url: '/styles-provider-anywhere',
        kind: 'Component',
    },
    {
        title: 'StylesProviderBetterHomesGardens',
        content: 'Utility to provide the Better Homes & Gardens styles to the application.',
        url: '/styles-provider-better-homes-gardens',
        kind: 'Component',
    },
    {
        title: 'StylesProviderCartus',
        content: 'Utility to provide the Cartus styles to the application.',
        url: '/styles-provider-cartus',
        kind: 'Component',
    },
    {
        title: 'StylesProviderCentury21',
        content: 'Utility to provide the Century 21 styles to the application.',
        url: '/styles-provider-century21',
        kind: 'Component',
    },
    {
        title: 'StylesProviderColdwellBanker',
        content: 'Utility to provide the Coldwell Banker styles to the application.',
        url: '/styles-provider-coldwell-banker',
        kind: 'Component',
    },
    {
        title: 'StylesProviderCorcoran',
        content: 'Utility to provide the Corcoran styles to the application.',
        url: '/styles-provider-corcoran',
        kind: 'Component',
    },
    {
        title: 'StylesProviderDenaliBoss',
        content: 'Utility to provide the Denali Boss styles to the application.',
        url: '/styles-provider-denali-boss',
        kind: 'Component',
    },
    {
        title: 'StylesProviderEra',
        content: 'Utility to provide the ERA styles to the application.',
        url: '/styles-provider-era',
        kind: 'Component',
    },
    {
        title: 'StylesProviderSothebys',
        content: "Utility to provide the Sotheby's styles to the application.",
        url: '/styles-provider-sothebys',
        kind: 'Component',
    },
    {
        title: 'Switch',
        content:
            'A control element that allows users to toggle between two states, typically representing on/off and inherits immediate reaction in each state. This is the base element and if used directly you must wrap it with a label. This will more often be used in the SwitchOption or SwitchGroup component. name The [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) of the control. undefined value The value of the control. undefined disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false aria-label The aria-label for the element. undefined onClick The function to call when the element is clicked. undefined checked Marks the control as checked. false onChange The function to call when the control is checked or unchecked. undefined',
        url: '/switch',
        kind: 'Component',
    },
    {
        title: 'SwitchGroup',
        content:
            'A group of switches that allows users to choose one or more items from a list or turn an feature on or off. name The [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) of the control. undefined aria-label The aria-label for the element. undefined onChange The function to call when the switches are changed. undefined options The options for the switches. undefined values The values of the switches in the on state. undefined value The value of the control. undefined label The label of the field. Also used as the aria-label of the checkbox. undefined description The description of the field. undefined',
        url: '/switch-group',
        kind: 'Component',
    },
    {
        title: 'SwitchOption',
        content:
            'A control that allows users to choose one or more items from a list or turn an feature on or off. name The [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) of the control. undefined value The value of the control. undefined disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false onChange The function to call when the control is checked or unchecked. undefined onClick The function to call when the element is clicked. undefined checked Marks the control as checked. false label The label of the field. Also used as the aria-label of the checkbox. undefined size The size of the control option label. undefined description The description of the field. undefined',
        url: '/switch-option',
        kind: 'Component',
    },
    {
        title: 'TabGroup',
        content:
            "Navigation tool that organizes content across different screens and views. options The tabs to display. Each tab has a label and an optional leading icon. undefined value The id of the selected tab. undefined onChange The function to call when the tab is clicked. undefined size The size of the tabs. medium width When 'fill' the options will fill the width of the container. When 'hug', the options will be as wide as their\ncontent. hug showTrail When width is 'hug' this determines if the trailing underline should be showing. When width is 'fill' this\nproperty isn't applicable. false label The label of the tab. This is the text that will be displayed on the tab. undefined disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false value The value of the tab. If not provided, the label will be used as the value. undefined icon The icon to display on the left side of the tab. undefined iconActive The icon to display on the left side of the tab when the tab is active. undefined badge The badge count to display on the tab. undefined",
        url: '/tab-group',
        kind: 'Component',
    },
    {
        title: 'Table',
        content:
            'Component description coming soon. rows The data of the table. undefined columns The columns of the table. undefined',
        url: '/table',
        kind: 'Component',
    },
    {
        title: 'Tag',
        content:
            'A non-interactive visual indicators to draw attention or categorization of a component. as The element type to render as. span children The content of the tag. undefined size The size of the tag. small color The color of the tag. white variant The display variant of the tag. flat wrap Whether the tag should wrap its content.\n\n(Not recommended) false',
        url: '/tag',
        kind: 'Component',
    },
    {
        title: 'Textarea',
        content:
            'A component that allows users to input large amounts of text that could span multiple lines. required Determines if the element is [required](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required). false id The id of the element. If not provided one will be generated. undefined invalid Marks the element as invalid and displays error state theme. false disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false aria-label The aria-label for the element. undefined readOnly Determines if the element is [readonly](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly). false onChange Callback when the value of the field changes. undefined size The size of the field. medium value The value of the field. undefined name The textarea control name of the field. undefined innerRef The ref of the field. undefined placeholder The placeholder of the field. undefined maxLength The maximum number of characters that the field will accept. undefined minRows The minimum number of rows that the textarea should have. If set the textarea will automatically grow and shrink\nto fit the content. undefined maxRows The maximum number of rows that the textarea should have. If set the textarea will automatically grow and shrink\nto fit the content. undefined',
        url: '/textarea',
        kind: 'Component',
    },
    {
        title: 'TextareaField',
        content:
            'A component that allows users to input large amounts of text that could span multiple lines.\n\nThis component takes properties from the FormField and Textarea components. label The label of the field. undefined errorMessage Marks the element as invalid and displays error message.\n\nWhen an element is invalid it must display an error message explaining why it is invalid. undefined helperText The helperText of the field. undefined controlId The id of the control. undefined required Determines if the element is [required](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required). false id The id of the element. If not provided one will be generated. undefined invalid Marks the element as invalid and displays error state theme. false disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false aria-label The aria-label for the element. undefined readOnly Determines if the element is [readonly](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly). false onChange Callback when the value of the field changes. undefined size The size of the field. medium value The value of the field. undefined name The textarea control name of the field. undefined innerRef The ref of the field. undefined placeholder The placeholder of the field. undefined maxLength The maximum number of characters that the field will accept. undefined minRows The minimum number of rows that the textarea should have. If set the textarea will automatically grow and shrink\nto fit the content. undefined maxRows The maximum number of rows that the textarea should have. If set the textarea will automatically grow and shrink\nto fit the content. undefined',
        url: '/textarea-field',
        kind: 'Component',
    },
    {
        title: 'TextField',
        content:
            'A text input that allows users to enter text, numbers or symbols in a singular line.\n\nThis component takes properties from the FormField and TextInput components. name The [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) of the control. undefined required Determines if the element is [required](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required). false type The type of the input. undefined value The value of the control. undefined invalid Marks the element as invalid and displays error state theme. false disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false size The size of the element. medium onChange Callback when the value of the field changes. undefined autoComplete Specifies if user agent has any permission to provide automated assistance in filling out form field values.\nhttps://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete off placeholder The placeholder of the field. undefined readOnly Determines if the element is [readonly](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly). false leading The leading element to display in the field. undefined trailing The trailing element to display in the field. undefined inputRef The ref of the input. undefined label The label of the field. undefined errorMessage Marks the element as invalid and displays error message.\n\nWhen an element is invalid it must display an error message explaining why it is invalid. undefined helperText The helperText of the field. undefined labelTrailing The trailing element of the label. undefined controlId The id of the control. undefined',
        url: '/text-field',
        kind: 'Component',
    },
    {
        title: 'TextInput',
        content:
            'A text input that allows users to enter text, numbers or symbols in a singular line. This is the base element and is not intended to be used directly. Use the TextField component. name The [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) of the control. undefined required Determines if the element is [required](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required). false id The id of the element. If not provided one will be generated. undefined value The value of the control. undefined invalid Marks the element as invalid and displays error state theme. false disabled Determines if the element is [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled). false size The size of the element. medium aria-label The aria-label for the element. undefined readOnly Determines if the element is [readonly](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly). false onChange Callback when the value of the field changes. undefined containerRef The ref of the container. undefined inputRef The ref of the input. undefined trailing The trailing element to display in the field. undefined leading The leading element to display in the field. undefined placeholder The placeholder of the field. undefined type The type of the input. undefined autoComplete Specifies if user agent has any permission to provide automated assistance in filling out form field values.\nhttps://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete off',
        url: '/text-input',
        kind: 'Component',
    },
    {
        title: 'TimePicker',
        content: 'Component description coming soon. children The content of the timepicker. undefined',
        url: '/time-picker',
        kind: 'Component',
    },
    {
        title: 'ToggleOption',
        content:
            'A utility component that wraps a checkbox, radio, and switch. label The label of the field. Also used as the aria-label of the checkbox. undefined description The description of the field. undefined children The control element to use. undefined size The size of the control option label. undefined',
        url: '/toggle-option',
        kind: 'Component',
    },
    {
        title: 'Tooltip',
        content:
            'Brief message that provide additional guidance and helps users perform an action if needed. placement The placement of the tooltip. top label The tooltip content. undefined children A single element that will trigger the tooltip when hovered over. undefined disabled Determines if the tooltip is disabled. undefined tail Determines if the tooltip should hide the tail. true',
        url: '/tooltip',
        kind: 'Component',
    },
    {
        title: 'TopNavigation',
        content: 'Component description coming soon. children The content of the top navigation. undefined',
        url: '/top-navigation',
        kind: 'Component',
    },
    {
        title: 'Txt',
        content:
            'A text component that applies the correct font styles based on the variant and size. variant as The element type to render as. span children The content to render. undefined variant The variant to use. body-base id The id of the element. undefined',
        url: '/txt',
        kind: 'Component',
    },
    {
        title: 'useCheckboxGroupState',
        content: 'A hook to manage the state of a group of checkboxes. Used alongside the CheckboxGroup component.',
        url: '/hooks#use-checkbox-group-state',
        kind: 'Hook',
    },
    {
        title: 'useCheckboxState',
        content: 'A hook to manage the state of a single checkbox. Used alongside the Checkbox component.',
        url: '/hooks#use-checkbox-state',
        kind: 'Hook',
    },
    {
        title: 'useKeyboardNavigation',
        content: 'This hook provides keyboard navigation for a list of elements. Used inside the Dropdown component.',
        url: '/hooks#use-keyboard-navigation',
        kind: 'Hook',
    },
    {
        title: 'useModalState',
        content: 'A hook to manage the state of a modal.',
        url: '/hooks#use-modal-state',
        kind: 'Hook',
    },
    {
        title: 'useOutsideClick',
        content:
            'A hook which calls a method when a click occurs outside of the provided ref. Used inside the Dropdown and Modal components.',
        url: '/hooks#use-outside-click',
        kind: 'Hook',
    },
    {
        title: 'useRadioState',
        content: 'A hook to manage the state of a single radio. Used alongside the Radio component.',
        url: '/hooks#use-radio-state',
        kind: 'Hook',
    },
    {
        title: 'useSwitchGroupState',
        content: 'A hook to manage the state of a group of switches. Used alongside the SwitchGroup component.',
        url: '/hooks#use-switch-group-state',
        kind: 'Hook',
    },
    {
        title: 'useTimeout',
        content: 'A hook that creates a timeout that is automatically cleared when the component is unmounted.',
        url: '/hooks#use-timeout',
        kind: 'Hook',
    },
] as const;
